heroku config:set MY_HEROKU_URL=$(heroku info -s | grep web_url | cut -d= -f2)
heroku config:set APP_KEYS=$(cat .env | grep APP_KEYS | cut -d= -f2-)
heroku config:set API_TOKEN_SALT=$(cat .env | grep API_TOKEN_SALT | cut -d= -f2)
heroku config:set ADMIN_JWT_SECRET=$(cat .env | grep ADMIN_JWT_SECRET | cut -d= -f2)
heroku config:set JWT_SECRET=$(cat .env | grep -w JWT_SECRET | cut -d= -f2)

heroku config:set AWS_BUCKET=$(cat .env | grep -w AWS_BUCKET | cut -d= -f2)
heroku config:set AWS_REGION=$(cat .env | grep -w AWS_REGION | cut -d= -f2)
heroku config:set AWS_ACCESS_SECRET=$(cat .env | grep -w AWS_ACCESS_SECRET | cut -d= -f2)
heroku config:set AWS_ACCESS_KEY_ID=$(cat .env | grep -w AWS_ACCESS_KEY_ID | cut -d= -f2)
